import { useState, useRef, useEffect } from 'react';
import {
  ChevronDown,
  Sparkles,
  Search,
  Database,
  AlertTriangle,
  Copy,
  Workflow
} from 'lucide-react';
import {
  OVERVIEW_STATS,
  UNRESOLVED_SECTION,
  AWAITING_CONFIRMATION,
  TABLES_TREE,
  OBJECT_DETAILS,
  REQUIREMENTS,
  RECONCILE_METRICS,
  RECONCILE_ONLY_POWERBI,
  RECONCILE_ONLY_WAREHOUSE,
  REVIEW_QUEUE,
  COPILOT_RESPONSES,
  type ModelObject
} from './mockData';

function App() {
  const [activeScreen, setActiveScreen] = useState<'overview' | 'model' | 'requirements' | 'reconcile' | 'review'>('model');
  const [isCopilotOpen, setIsCopilotOpen] = useState(true);
  const [isDarkMode, setIsDarkMode] = useState(true);
  
  // Model Screen state
  const [modelSearch, setModelSearch] = useState('');
  const [expandedTables, setExpandedTables] = useState<Record<string, boolean>>({
    'QC Metrics': true,
    'TestResult': true
  });
  const [selectedObject, setSelectedObject] = useState<ModelObject | null>(null);

  // Requirements screen state
  const [expandedRequirements, setExpandedRequirements] = useState<Record<string, boolean>>({});
  const [reqFilter, setReqFilter] = useState<'all' | 'high' | 'medium' | 'low'>('all');
  const [reqDocType, setReqDocType] = useState<'BRD' | 'FRD'>('BRD');

  // Copilot interactive state
  const [copilotInput, setCopilotInput] = useState('');
  const [chatLog, setChatLog] = useState<{ sender: 'user' | 'copilot'; text: string; isThinking?: boolean }[]>([]);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Review copy state
  const [copiedQueue, setCopiedQueue] = useState(false);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatLog]);

  const toggleTableExpand = (tableName: string) => {
    setExpandedTables(prev => ({
      ...prev,
      [tableName]: !prev[tableName]
    }));
  };

  const handleObjectSelect = (name: string, tableName: string, type: 'column' | 'measure') => {
    if (OBJECT_DETAILS[name]) {
      setSelectedObject(OBJECT_DETAILS[name]);
    } else {
      const basicDetail: ModelObject = {
        id: `${type}:${tableName}.${name}`,
        name,
        type,
        tableName,
        description: `Autogenerated schema documentation for ${tableName}[${name}].`,
        upstream: [],
        downstream: [
          { name: `Join: ${tableName} -> TestResult`, type: 'table', path: 'TestResult' }
        ],
        fingerprint: `sha256:${Math.random().toString(16).substring(2, 10)}b8ac${Math.random().toString(16).substring(2, 6)}df09`
      };
      setSelectedObject(basicDetail);
    }
  };

  const handleCopilotSubmit = (text: string) => {
    if (!text.trim()) return;
    const cleanText = text.toLowerCase().trim();
    
    // Add user message
    const newLog = [...chatLog, { sender: 'user' as const, text }];
    setChatLog(newLog);
    setCopilotInput('');

    // Add thinking state
    setChatLog(prev => [...prev, { sender: 'copilot', text: 'Analyzing semantic graph...', isThinking: true }]);

    setTimeout(() => {
      let reply = "I couldn't find a direct correlation in the current semantic graph. Try asking: \"What does OOS Rate measure?\" or \"What breaks if I change Tests Performed?\"";
      
      // Basic fuzzy matching
      for (const [key, responseValue] of Object.entries(COPILOT_RESPONSES)) {
        if (cleanText.includes(key)) {
          reply = responseValue;
          break;
        }
      }

      setChatLog(prev => {
        const filtered = prev.filter(item => !item.isThinking);
        return [...filtered, { sender: 'copilot' as const, text: reply }];
      });
    }, 700);
  };

  const handleCopyQueue = () => {
    const queueText = JSON.stringify(REVIEW_QUEUE, null, 2);
    navigator.clipboard.writeText(queueText).then(() => {
      setCopiedQueue(true);
      setTimeout(() => setCopiedQueue(false), 2000);
    });
  };

  const toggleReqExpand = (reqId: string) => {
    setExpandedRequirements(prev => ({
      ...prev,
      [reqId]: !prev[reqId]
    }));
  };

  // Filter requirements based on confidence badge selection
  const filteredRequirements = REQUIREMENTS.filter(req => {
    if (reqFilter === 'all') return true;
    return req.confidence.toLowerCase() === reqFilter;
  });

  return (
    <div className={`min-h-screen flex flex-col font-mono text-xs overflow-hidden select-none ${isDarkMode ? 'bg-[#0d0b0a] text-[#f7f4f0]' : 'bg-[#f5f2eb] text-[#0d0b0a] transition-all'}`}>
      
      {/* GLOBAL TOP-MOST BAR */}
      <header className="h-10 border-b border-[#2c2520] px-4 flex items-center justify-between shrink-0 bg-[#080706]">
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1.5 text-[#c9a15f] hover:text-[#e5ba73] cursor-pointer">
            <span className="font-bold text-xs tracking-wider">Concordance — semantic layer interface</span>
            <ChevronDown size={11} className="text-[#968a80]" />
          </div>
          <div className="h-4 w-px bg-[#2c2520]" />
          <span className="text-[#968a80] italic text-[10px]">Content is user-generated and unverified.</span>
        </div>

        <div className="flex items-center gap-3">
          <div className="w-6 h-6 rounded-full bg-[#5d3ab7] text-white flex items-center justify-center font-bold text-[10px] cursor-pointer" title="User Profile">
            AP
          </div>
          <button className="text-[10px] text-[#968a80] hover:text-[#f7f4f0] bg-[#1a1614] border border-[#2c2520] px-2 py-0.5 rounded">
            Share
          </button>
        </div>
      </header>

      {/* AMBER BANNER STRIP */}
      <div className="bg-[#2a2012] border-b border-[#4d3a21] text-[#c9a15f] py-1.5 px-4 text-[10px] flex items-center gap-2 shrink-0 overflow-hidden">
        <span className="inline-block w-1.5 h-1.5 rounded-full bg-[#c9a15f] animate-pulse" />
        <span className="truncate">Static snapshot of a real extraction — every figure below came from the model, but nothing here is live and the copilot needs a running server.</span>
      </div>

      {/* SECONDARY SUB-HEADER BAR */}
      <div className="h-11 border-b border-[#2c2520] px-4 flex items-center justify-between bg-[#0b0908] shrink-0">
        <div className="flex items-center gap-1.5 text-xs">
          <span className="text-[#69615a]">Concordance</span>
          <span className="text-[#2c2520]">|</span>
          <span className="text-[#f7f4f0] font-bold">QualityControl</span>
        </div>

        <div className="flex items-center gap-3">
          <span className="text-[#968a80] text-[10px]">20 measures · 6 joins</span>
          
          <button 
            onClick={() => setIsCopilotOpen(!isCopilotOpen)}
            className={`flex items-center gap-1 px-2.5 py-0.5 rounded border text-[10px] transition-all font-semibold ${isCopilotOpen ? 'bg-[#0f2d24] border-[#10b981] text-[#34d399]' : 'bg-[#1a1614] border-[#2c2520] text-[#968a80]'}`}
          >
            <Sparkles size={10} />
            <span>copilot</span>
          </button>
          
          <button 
            onClick={() => setIsDarkMode(!isDarkMode)}
            className="px-2.5 py-0.5 rounded border border-[#2c2520] text-[#968a80] hover:text-[#f7f4f0] text-[10px] bg-[#1a1614]"
          >
            {isDarkMode ? 'light' : 'dark'}
          </button>
        </div>
      </div>

      {/* BODY WORKSPACE */}
      <div className="flex-1 flex overflow-hidden">
        
        {/* SIDEBAR NAVIGATION */}
        <nav className="w-[150px] border-r border-[#2c2520] bg-[#0b0a09] flex flex-col justify-between shrink-0 p-3">
          <div className="space-y-1">
            {[
              { id: 'overview', label: 'Overview' },
              { id: 'model', label: 'Model' },
              { id: 'requirements', label: 'Requirements' },
              { id: 'reconcile', label: 'Reconcile' },
              { id: 'review', label: 'Review' }
            ].map(item => {
              const active = activeScreen === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => setActiveScreen(item.id as any)}
                  className={`w-full text-left px-2 py-1.5 rounded transition-all text-xs ${active ? 'bg-[#1e1914] text-[#c9a15f] font-bold border-l-2 border-[#c9a15f]' : 'text-[#968a80] hover:text-[#f7f4f0] hover:bg-[#12100f]'}`}
                >
                  {item.label}
                </button>
              );
            })}
          </div>

          <div className="p-2 bg-[#0e0d0c] rounded border border-[#2c2520] text-[8px] text-[#69615a] space-y-0.5">
            <div>ENGINE: <span className="text-[#968a80]">tmdl-v2</span></div>
            <div>VER: <span className="text-[#968a80]">0.42.1</span></div>
          </div>
        </nav>

        {/* MAIN PANEL CONTENT */}
        <main className="flex-1 overflow-y-auto bg-[#0d0b0a] flex flex-col p-6 min-w-0 select-text">
          
          {/* SCREEN 1: OVERVIEW */}
          {activeScreen === 'overview' && (
            <div className="space-y-6 max-w-5xl">
              <div>
                <h1 className="text-lg font-bold text-[#f7f4f0] tracking-wide">QualityControl</h1>
                <p className="text-[#968a80] mt-0.5 text-xs">tmdl · 6 user tables of {OVERVIEW_STATS.tables}</p>
              </div>

              {/* 6 Stats row */}
              <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
                {[
                  { label: 'TABLES', val: OVERVIEW_STATS.tables },
                  { label: 'COLUMNS', val: OVERVIEW_STATS.columns },
                  { label: 'MEASURES', val: OVERVIEW_STATS.measures },
                  { label: 'JOINS', val: OVERVIEW_STATS.joins },
                  { label: 'HIERARCHIES', val: OVERVIEW_STATS.hierarchies },
                  { label: 'NEEDS REVIEW', val: OVERVIEW_STATS.needsReview, alert: true }
                ].map((stat, i) => (
                  <div key={i} className="p-3 bg-[#131110] border border-[#2c2520] rounded flex flex-col justify-between min-h-[70px]">
                    <div className="text-[9px] text-[#968a80] tracking-wider font-semibold uppercase">{stat.label}</div>
                    <div className={`text-xl font-bold mt-1 tabular-nums ${stat.alert ? 'text-[#c9a15f]' : 'text-[#f7f4f0]'}`}>
                      {stat.val}
                    </div>
                  </div>
                ))}
              </div>

              {/* Warnings panel */}
              <div className="p-4 bg-[#131110] border border-[#2c2520] rounded space-y-2">
                <div className="text-[9px] text-[#968a80] tracking-wider uppercase font-bold">WHAT WAS NOT READ OR RESOLVED</div>
                <div className="text-xs text-[#968a80] bg-[#0d0b0a] p-3 rounded border border-[#2c2520] font-mono leading-relaxed">
                  {UNRESOLVED_SECTION.warningText}
                </div>
              </div>

              {/* Awaiting Confirmation (low confidence) */}
              <div className="space-y-3">
                <div className="text-[9px] text-[#968a80] tracking-wider uppercase font-bold">AWAITING CONFIRMATION ({AWAITING_CONFIRMATION.length})</div>
                
                <div className="space-y-2">
                  {AWAITING_CONFIRMATION.map(item => (
                    <div key={item.id} className="p-4 bg-[#131110] border border-[#2c2520] rounded flex flex-col gap-2">
                      <div className="flex items-center gap-2">
                        <span className="text-[#c95f5f] font-bold text-xs">{item.id}</span>
                        <span className="text-[8px] bg-[#301616] text-[#c95f5f] px-1 py-0.2 rounded border border-[#4f2424] font-semibold uppercase">low</span>
                        <span className="text-[8px] bg-[#222] text-[#968a80] px-1.5 py-0.2 rounded border border-[#2c2520]">{item.rule}</span>
                      </div>
                      <div className="text-xs text-[#968a80] leading-relaxed" dangerouslySetInnerHTML={{ __html: item.textHtml }} />
                      <div className="text-[11px] text-[#69615a] italic">{item.explanation}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Footer */}
              <div className="pt-6 border-t border-[#2c2520] text-[#69615a] flex items-center justify-between text-[10px]">
                <span>drift not configured · reconcile configured</span>
              </div>
            </div>
          )}

          {/* SCREEN 2: MODEL */}
          {activeScreen === 'model' && (
            <div className="flex-1 flex flex-col md:flex-row gap-5 min-h-0">
              
              {/* Expandable Object Tree */}
              <div className="w-full md:w-[260px] flex flex-col bg-[#131110] border border-[#2c2520] rounded min-h-0 shrink-0">
                <div className="p-3 border-b border-[#2c2520] space-y-2">
                  <div className="relative">
                    <Search className="absolute left-2 top-2 text-[#69615a]" size={11} />
                    <input
                      type="text"
                      placeholder="Filter objects"
                      value={modelSearch}
                      onChange={(e) => setModelSearch(e.target.value)}
                      className="w-full bg-[#0d0b0a] border border-[#2c2520] rounded pl-7 pr-2.5 py-1 text-xs text-[#f7f4f0] focus:outline-none focus:border-[#c9a15f] placeholder-[#69615a] font-mono"
                    />
                  </div>
                </div>

                <div className="flex-1 overflow-y-auto p-2 space-y-1">
                  {TABLES_TREE.map(table => {
                    const isExpanded = !!expandedTables[table.name];
                    const filteredChildren = table.children.filter(child => 
                      child.name.toLowerCase().includes(modelSearch.toLowerCase()) ||
                      table.name.toLowerCase().includes(modelSearch.toLowerCase())
                    );

                    if (modelSearch && filteredChildren.length === 0 && !table.name.toLowerCase().includes(modelSearch.toLowerCase())) {
                      return null;
                    }

                    return (
                      <div key={table.name} className="space-y-0.5">
                        <button
                          onClick={() => toggleTableExpand(table.name)}
                          className="w-full flex items-center justify-between p-1 rounded hover:bg-[#1c1816] text-[#968a80] hover:text-[#f7f4f0]"
                        >
                          <div className="flex items-center gap-1">
                            <span className="text-[10px] font-mono text-[#69615a] w-3 text-center">
                              {isExpanded ? '−' : '+'}
                            </span>
                            <span className={`font-semibold ${table.hasMeasures ? 'text-[#c9a15f]' : 'text-[#f7f4f0]'}`}>
                              {table.name}
                            </span>
                            {table.hasMeasures && (
                              <span className="text-[8px] text-[#34d399] bg-[#0c241c] border border-[#10b981] px-1 rounded ml-1 scale-90">
                                fx
                              </span>
                            )}
                          </div>
                          <span className="text-[9px] text-[#69615a] font-mono">{table.childCount}</span>
                        </button>

                        {isExpanded && (
                          <div className="pl-4 border-l border-[#2c2520] ml-2.5 space-y-0.5">
                            {filteredChildren.map(child => {
                              const isSelected = selectedObject?.name === child.name && selectedObject?.tableName === table.name;
                              return (
                                <button
                                  key={child.name}
                                  onClick={() => handleObjectSelect(child.name, table.name, child.type)}
                                  className={`w-full flex items-center justify-between px-2 py-0.5 rounded text-left ${
                                    isSelected 
                                      ? 'bg-[#211a14] text-[#c9a15f] border-l-2 border-[#c9a15f]' 
                                      : 'text-[#69615a] hover:text-[#f7f4f0]'
                                  }`}
                                >
                                  <span className="truncate">{child.name}</span>
                                  <span className="text-[7px] opacity-40 select-none">{child.type.substring(0, 3)}</span>
                                </button>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
                
                <div className="p-2 border-t border-[#2c2520] bg-[#0d0b0a] text-[#69615a] text-[8px] text-center font-mono">
                  68 objects · 121 edges
                </div>
              </div>

              {/* Right Detail Pane */}
              <div className="flex-1 flex flex-col bg-[#131110] border border-[#2c2520] rounded min-w-0">
                {selectedObject ? (
                  <div className="flex-1 flex flex-col min-h-0 overflow-y-auto p-5 space-y-5">
                    
                    {/* Header */}
                    <div className="border-b border-[#2c2520] pb-4 flex flex-col sm:flex-row justify-between sm:items-center gap-3">
                      <div>
                        <div className="flex items-center gap-1.5">
                          <span className={`text-[8px] px-1 py-0.2 rounded border font-semibold ${selectedObject.type === 'measure' ? 'bg-[#0f2d24] border-[#10b981] text-[#34d399]' : 'bg-[#1e1a16] border-[#42372c] text-[#c9a15f]'}`}>
                            {selectedObject.type.toUpperCase()}
                          </span>
                          <span className="text-[#968a80] text-xs font-bold">{selectedObject.tableName}</span>
                        </div>
                        <h2 className="text-base font-bold text-[#c9a15f] mt-1">{selectedObject.name}</h2>
                      </div>
                      <div className="text-right">
                        <span className="text-[9px] text-[#69615a] font-mono block">SHA-256 FINGERPRINT</span>
                        <code className="text-[9px] text-[#968a80] select-all bg-[#0d0b0a] px-1.5 py-0.5 rounded border border-[#2c2520] font-mono block mt-1 truncate max-w-[240px]">
                          {selectedObject.fingerprint}
                        </code>
                      </div>
                    </div>

                    {/* Description */}
                    {selectedObject.description && (
                      <div className="space-y-1.5">
                        <div className="text-[9px] text-[#968a80] uppercase tracking-wider font-bold">Description</div>
                        <p className="text-xs text-[#f7f4f0] bg-[#0d0b0a] p-3 rounded border border-[#2c2520] leading-relaxed">
                          {selectedObject.description}
                        </p>
                      </div>
                    )}

                    {/* DAX Formula */}
                    {selectedObject.type === 'measure' && selectedObject.formula && (
                      <div className="space-y-1.5">
                        <span className="text-[9px] text-[#968a80] uppercase tracking-wider font-bold">DAX expression</span>
                        <div className="bg-[#0d0b0a] border border-[#2c2520] rounded p-3 overflow-x-auto">
                          <pre className="text-xs text-[#c9a15f] leading-5 whitespace-pre">
                            {selectedObject.cleanedFormula}
                          </pre>
                        </div>
                      </div>
                    )}

                    {/* Dependencies Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                      
                      <div className="border border-[#2c2520] rounded bg-[#0d0b0a] p-4 space-y-3">
                        <div className="flex items-center gap-2 border-b border-[#2c2520] pb-2">
                          <Workflow size={11} className="text-[#968a80]" />
                          <span className="text-[9px] font-bold text-[#f7f4f0] uppercase tracking-wider">Upstream Dependencies ({selectedObject.upstream.length})</span>
                        </div>
                        {selectedObject.upstream.length > 0 ? (
                          <div className="space-y-1">
                            {selectedObject.upstream.map((dep, index) => (
                              <div key={index} className="flex items-center justify-between text-xs py-1 px-2 bg-[#131110] rounded border border-[#2c2520]">
                                <span className="text-[#f7f4f0]">{dep.name}</span>
                                <span className="text-[8px] bg-[#1a1614] border border-[#2c2520] px-1 rounded text-[#c9a15f]">{dep.type}</span>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <div className="text-xs text-[#69615a] italic">No upstream semantic layers detected.</div>
                        )}
                      </div>

                      <div className="border border-[#2c2520] rounded bg-[#0d0b0a] p-4 space-y-3">
                        <div className="flex items-center gap-2 border-b border-[#2c2520] pb-2">
                          <AlertTriangle size={11} className="text-[#c95f5f]" />
                          <span className="text-[9px] font-bold text-[#c95f5f] uppercase tracking-wider">Breakage Downstream ({selectedObject.downstream.length})</span>
                        </div>
                        {selectedObject.downstream.length > 0 ? (
                          <div className="space-y-1">
                            {selectedObject.downstream.map((dep, index) => (
                              <div key={index} className="flex items-center justify-between text-xs py-1 px-2 bg-[#211616] rounded border border-[#4f2424]">
                                <span className="text-[#c95f5f] font-semibold">{dep.name}</span>
                                <span className="text-[8px] bg-[#301616] border border-[#4f2424] px-1 rounded text-[#c95f5f]">{dep.type}</span>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <div className="text-xs text-[#69615a] italic">No downstream dependencies breakages mapped.</div>
                        )}
                      </div>

                    </div>

                  </div>
                ) : (
                  <div className="flex-1 flex items-center justify-center text-center p-8">
                    <div className="space-y-2">
                      <Database size={24} className="text-[#2c2520] mx-auto" />
                      <div className="text-xs text-[#968a80]">Select an object to see how it is defined and what depends on it.</div>
                    </div>
                  </div>
                )}
                
                <div className="p-3 border-t border-[#2c2520] text-[#69615a] text-[9px] flex items-center justify-between bg-[#0e0c0b]">
                  <span>Source TMDL: C:\git\QualityControl\QC_Metrics.tmdl</span>
                  <span>Extracted: 2026-08-24 16:15:31</span>
                </div>
              </div>

            </div>
          )}

          {/* SCREEN 3: REQUIREMENTS */}
          {activeScreen === 'requirements' && (
            <div className="space-y-6 max-w-5xl">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h1 className="text-lg font-bold text-[#f7f4f0] tracking-wide">Business requirements</h1>
                  <p className="text-[#968a80] mt-0.5 text-xs">Derived from the model by code, not written by a language model.</p>
                </div>

                {/* BRD/FRD tab selection */}
                <div className="flex bg-[#131110] border border-[#2c2520] rounded p-0.5 select-none shrink-0 font-mono text-[9px] font-semibold">
                  <button
                    onClick={() => setReqDocType('BRD')}
                    className={`px-2 py-0.5 rounded transition-all ${reqDocType === 'BRD' ? 'bg-[#0f2d24] border border-[#10b981] text-[#34d399]' : 'text-[#69615a] hover:text-[#968a80]'}`}
                  >
                    BRD
                  </button>
                  <button
                    onClick={() => setReqDocType('FRD')}
                    className={`px-2 py-0.5 rounded transition-all ${reqDocType === 'FRD' ? 'bg-[#0f2d24] border border-[#10b981] text-[#34d399]' : 'text-[#69615a] hover:text-[#968a80]'}`}
                  >
                    FRD
                  </button>
                </div>
              </div>

              {/* Requirement statistics */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { label: 'REQUIREMENTS', val: 31 },
                  { label: 'STATED BY THE MODEL', val: 25 },
                  { label: 'FROM A STRUCTURAL RULE', val: 5 },
                  { label: 'INFERRED - NEEDS A PERSON', val: 1, alert: true }
                ].map((stat, i) => (
                  <div key={i} className="p-3 bg-[#131110] border border-[#2c2520] rounded flex flex-col justify-between min-h-[65px]">
                    <div className="text-[8px] text-[#968a80] tracking-wider uppercase font-semibold">{stat.label}</div>
                    <div className={`text-xl font-bold mt-1 ${stat.alert ? 'text-[#c95f5f]' : 'text-[#f7f4f0]'}`}>
                      {stat.val}
                    </div>
                  </div>
                ))}
              </div>

              {/* Show Filters */}
              <div className="flex items-center gap-2 text-[9px] font-semibold">
                <span className="text-[#69615a] uppercase">SHOW</span>
                <div className="flex border border-[#2c2520] rounded p-0.5 bg-[#131110]">
                  {(['all', 'high', 'medium', 'low'] as const).map(f => (
                    <button
                      key={f}
                      onClick={() => setReqFilter(f)}
                      className={`px-2 py-0.5 rounded uppercase ${reqFilter === f ? 'bg-[#1e1914] text-[#c9a15f]' : 'text-[#968a80] hover:text-[#f7f4f0]'}`}
                    >
                      {f}
                    </button>
                  ))}
                </div>
              </div>

              {/* Cards List */}
              <div className="space-y-3">
                {filteredRequirements.map(req => {
                  const isExpanded = !!expandedRequirements[req.id];
                  return (
                    <div key={req.id} className="bg-[#131110] border border-[#2c2520] rounded hover:border-[#332b25] transition-all">
                      <div className="p-4 flex flex-col sm:flex-row justify-between items-start gap-4">
                        <div className="space-y-1.5">
                          <div className="flex items-center gap-2">
                            <span className="font-bold text-[#c9a15f]">{req.id}</span>
                            <span className="text-[8px] bg-[#222] border border-[#2c2520] text-[#968a80] px-1.5 py-0.2 rounded font-mono">
                              {req.rule}
                            </span>
                          </div>
                          <div className="text-xs text-[#f7f4f0] leading-relaxed" dangerouslySetInnerHTML={{ __html: req.textHtml }} />
                          <p className="text-[11px] text-[#69615a] italic">{req.explanation}</p>
                        </div>

                        <div className="shrink-0 text-right">
                          <span className={`inline-block text-[8px] font-bold px-2 py-0.5 rounded border ${
                            req.confidence === 'HIGH' ? 'bg-[#181d19] border-[#2c4f34] text-[#5f9c6f]' : 
                            req.confidence === 'MEDIUM' ? 'bg-[#29221a] border-[#4f3d24] text-[#c9a15f]' : 
                            'bg-[#301616] border-[#4f2424] text-[#c95f5f]'
                          }`}>
                            {req.confidence.toLowerCase()}
                          </span>
                        </div>
                      </div>

                      {/* Expandable footers */}
                      <div className="border-t border-[#2c2520] bg-[#0c0a09]">
                        <button
                          onClick={() => toggleReqExpand(req.id)}
                          className="w-full flex items-center justify-between px-4 py-1.5 text-[#69615a] hover:text-[#968a80] text-[9px]"
                        >
                          <span className="font-semibold">
                            {isExpanded ? '−' : '+'} bound to {req.boundObjects.length} object
                          </span>
                        </button>
                        {isExpanded && (
                          <div className="px-6 py-2 border-t border-[#2c2520] bg-[#090807] space-y-1 font-mono text-[10px] text-[#968a80]">
                            {req.boundObjects.map((obj, idx) => (
                              <div key={idx} className="hover:underline cursor-pointer" onClick={() => {
                                setActiveScreen('model');
                                const base = obj.split('.').pop() || obj;
                                const tab = obj.split('.')[0] || '';
                                handleObjectSelect(base, tab, 'column');
                              }}>
                                {obj}
                              </div>
                            ))}
                          </div>
                        )}
                      </div>

                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* SCREEN 4: RECONCILE */}
          {activeScreen === 'reconcile' && (
            <div className="space-y-6 max-w-6xl">
              <div>
                <h1 className="text-lg font-bold text-[#f7f4f0] tracking-wide">Cross-platform reconciliation</h1>
                <p className="text-[#968a80] mt-0.5 text-xs">QualityControl against quality_control.duckdb</p>
              </div>

              {/* 4 reconciliation stat cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { label: 'DEFINED ON BOTH', val: 6, border: 'border-[#2c2520] text-[#f7f4f0]' },
                  { label: 'DIVERGENT', val: 1, border: 'border-[#4f2424] text-[#c95f5f]' },
                  { label: 'NEEDS REVIEW', val: 1, border: 'border-[#4f3d24] text-[#c9a15f]' },
                  { label: 'CONSISTENT', val: 4, border: 'border-[#2c4f34] text-[#5f9c6f]' }
                ].map((stat, i) => (
                  <div key={i} className={`p-3 bg-[#131110] border rounded flex flex-col justify-between min-h-[65px] ${stat.border}`}>
                    <div className="text-[8px] text-[#968a80] tracking-wider uppercase font-semibold">{stat.label}</div>
                    <div className="text-xl font-bold mt-1 tabular-nums">{stat.val}</div>
                  </div>
                ))}
              </div>

              {/* Divergent section */}
              <div className="space-y-3">
                <div className="text-[9px] text-[#69615a] uppercase font-bold tracking-wider pb-1">
                  Divergent — these will report different numbers (1)
                </div>
                {RECONCILE_METRICS.filter(m => m.status === 'divergent').map(metric => (
                  <ReconcileMetricRow key={metric.name} metric={metric} />
                ))}
              </div>

              {/* Needs review section */}
              <div className="space-y-3">
                <div className="text-[9px] text-[#69615a] uppercase font-bold tracking-wider pb-1">
                  Needs review — differs, but may still agree (1)
                </div>
                {RECONCILE_METRICS.filter(m => m.status === 'needs review').map(metric => (
                  <ReconcileMetricRow key={metric.name} metric={metric} />
                ))}
              </div>

              {/* Consistent section */}
              <div className="space-y-3">
                {RECONCILE_METRICS.filter(m => m.status === 'consistent').map(metric => (
                  <ReconcileMetricRow key={metric.name} metric={metric} />
                ))}
              </div>

              {/* Only In lists columns */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-[#2c2520] pt-5">
                
                <div className="bg-[#131110] border border-[#2c2520] rounded p-4">
                  <div className="text-[9px] font-bold text-[#c9a15f] uppercase border-b border-[#2c2520] pb-2 mb-2 tracking-wider">
                    ONLY IN POWER_BI ({RECONCILE_ONLY_POWERBI.length})
                  </div>
                  <div className="space-y-1 overflow-y-auto max-h-[250px] pr-2">
                    {RECONCILE_ONLY_POWERBI.map(item => (
                      <div key={item} className="text-xs text-[#968a80] py-1 border-b border-[#1c1715] font-semibold">
                        {item}
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-[#131110] border border-[#2c2520] rounded p-4">
                  <div className="text-[9px] font-bold text-[#968a80] uppercase border-b border-[#2c2520] pb-2 mb-2 tracking-wider">
                    ONLY IN WAREHOUSE ({RECONCILE_ONLY_WAREHOUSE.length})
                  </div>
                  <div className="space-y-1">
                    {RECONCILE_ONLY_WAREHOUSE.map(item => (
                      <div key={item} className="text-xs text-[#69615a] py-1 border-b border-[#1c1715] font-mono">
                        {item}
                      </div>
                    ))}
                  </div>
                </div>

              </div>

            </div>
          )}

          {/* SCREEN 5: REVIEW */}
          {activeScreen === 'review' && (
            <div className="space-y-6 max-w-4xl">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h1 className="text-lg font-bold text-[#f7f4f0] tracking-wide">Awaiting confirmation</h1>
                  <p className="text-[#968a80] mt-0.5 text-xs">Review low-confidence inferred items needing human confirmation.</p>
                </div>
                
                <button
                  onClick={handleCopyQueue}
                  className="flex items-center gap-1.5 px-3 py-1 bg-[#1e1914] border border-[#c9a15f] text-[#c9a15f] font-bold rounded hover:bg-[#2c221a] cursor-pointer"
                >
                  <Copy size={11} />
                  <span>{copiedQueue ? 'COPIED!' : 'COPY THE QUEUE'}</span>
                </button>
              </div>

              <div className="space-y-3">
                {REVIEW_QUEUE.map(item => (
                  <div key={item.id} className="bg-[#131110] border border-[#2c2520] rounded p-4 space-y-3">
                    <div className="flex justify-between items-center border-b border-[#2c2520] pb-2">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-xs text-[#c9a15f]">{item.id}</span>
                        <span className="text-[8px] bg-[#301616] text-[#c95f5f] px-1.5 py-0.2 rounded border border-[#4f2424] font-semibold">REVIEW</span>
                      </div>
                      <span className="text-[9px] text-[#69615a] uppercase font-bold">{item.rule}</span>
                    </div>

                    <div className="space-y-2">
                      <div className="text-xs text-[#f7f4f0] leading-relaxed" dangerouslySetInnerHTML={{ __html: item.textHtml }} />
                      <div className="text-[11px] text-[#968a80] bg-[#0d0b0a] p-3 rounded border border-[#2c2520] font-mono leading-relaxed">
                        {item.explanation}
                      </div>
                    </div>

                    <div className="flex justify-between items-center text-[10px] pt-1.5 text-[#69615a]">
                      <span className="font-mono bg-[#0d0b0a] border border-[#2c2520] px-2 py-0.5 rounded text-[#968a80]">
                        {item.mapping}
                      </span>
                      <span className="font-mono">hash: <code className="text-[#968a80]">{item.hash}</code></span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

        </main>

        {/* RIGHT DOCKED COPILOT PANEL */}
        {isCopilotOpen && (
          <aside className="w-[340px] border-l border-[#2c2520] bg-[#0b0a09] flex flex-col justify-between shrink-0 h-full relative">
            
            <div className="p-3.5 border-b border-[#2c2520] bg-[#090807] flex items-center justify-between shrink-0 select-none">
              <div className="flex items-center gap-1.5">
                <Sparkles size={11} className="text-[#c9a15f]" />
                <span className="font-bold text-[#c9a15f] tracking-wider text-[10px] uppercase">COPILOT · QualityControl</span>
              </div>
              <button 
                onClick={() => setIsCopilotOpen(false)}
                className="text-[#69615a] hover:text-[#968a80] text-[10px] font-bold border border-[#2c2520] px-1 rounded bg-[#0d0b0a] cursor-pointer"
              >
                ✕
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4 select-text">
              
              {/* Intro Line */}
              <div className="p-3 bg-[#131110] border border-[#2c2520] rounded space-y-2">
                <p className="text-[10px] text-[#f7f4f0] leading-relaxed">
                  Ask about this model. Answers come from the graph, not from memory.
                </p>
                <div className="space-y-1.5 pt-2 border-t border-[#2c2520]">
                  <div className="text-[8px] text-[#69615a] uppercase font-bold tracking-widest">Example queries</div>
                  <div className="space-y-1">
                    {[
                      "What does OOS Rate measure?",
                      "What breaks if I change Tests Performed?",
                      "Which joins are inactive?"
                    ].map((promptText, i) => (
                      <button
                        key={i}
                        onClick={() => handleCopilotSubmit(promptText)}
                        className="w-full text-left text-[10px] text-[#c9a15f] hover:underline italic block py-0.5 transition-all cursor-pointer"
                      >
                        "{promptText}"
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Chat Thread */}
              <div className="space-y-4 font-mono text-[10px]">
                {chatLog.map((message, index) => (
                  <div 
                    key={index} 
                    className={`flex flex-col space-y-1 ${message.sender === 'user' ? 'items-end' : 'items-start'}`}
                  >
                    <span className="text-[8px] text-[#69615a] uppercase tracking-wider font-bold">
                      {message.sender === 'user' ? 'USER' : 'COPILOT'}
                    </span>
                    <div className={`p-2.5 rounded border leading-relaxed max-w-[95%] whitespace-pre-wrap ${
                      message.sender === 'user' 
                        ? 'bg-[#1d1712] border-[#42372c] text-[#c9a15f]' 
                        : 'bg-[#0d0b0a] border-[#2c2520] text-[#f7f4f0]'
                    }`}>
                      {message.isThinking ? (
                        <div className="flex items-center gap-1.5 py-1">
                          <span className="inline-block w-1.5 h-1.5 rounded-full bg-[#c9a15f] animate-bounce" style={{ animationDelay: '0ms' }} />
                          <span className="inline-block w-1.5 h-1.5 rounded-full bg-[#c9a15f] animate-bounce" style={{ animationDelay: '150ms' }} />
                          <span className="inline-block w-1.5 h-1.5 rounded-full bg-[#c9a15f] animate-bounce" style={{ animationDelay: '300ms' }} />
                        </div>
                      ) : (
                        message.text
                      )}
                    </div>
                  </div>
                ))}
                <div ref={chatEndRef} />
              </div>

            </div>

            {/* Input drawer box pinned */}
            <div className="p-3 border-t border-[#2c2520] bg-[#090807] shrink-0 select-none">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleCopilotSubmit(copilotInput);
                }}
                className="flex items-center gap-2"
              >
                <input
                  type="text"
                  placeholder="Ask about this model"
                  value={copilotInput}
                  onChange={(e) => setCopilotInput(e.target.value)}
                  className="flex-1 bg-[#0d0b0a] border border-[#2c2520] rounded px-3 py-1.5 text-xs text-[#f7f4f0] focus:outline-none focus:border-[#c9a15f] placeholder-[#69615a] font-mono"
                />
              </form>
            </div>

          </aside>
        )}

      </div>
    </div>
  );
}

// Subcomponent for Reconcile card block
interface ReconcileMetricRowProps {
  metric: typeof RECONCILE_METRICS[number];
}

function ReconcileMetricRow({ metric }: ReconcileMetricRowProps) {
  return (
    <div className="bg-[#131110] border border-[#2c2520] rounded p-4 space-y-3">
      
      <div className="flex justify-between items-center border-b border-[#2c2520] pb-2 select-none">
        <span className="font-bold text-xs text-[#f7f4f0]">{metric.name}</span>
        <span className={`text-[8px] font-bold px-1.5 py-0.2 rounded border uppercase ${
          metric.status === 'consistent' ? 'bg-[#181d19] border-[#2c4f34] text-[#5f9c6f]' :
          metric.status === 'needs review' ? 'bg-[#29221a] border-[#4f3d24] text-[#c9a15f]' :
          'bg-[#301616] border-[#4f2424] text-[#c95f5f]'
        }`}>
          {metric.status}
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        
        {/* Power BI panel */}
        <div className="space-y-1">
          <div className="text-[8px] font-semibold text-[#69615a] uppercase">POWER_BI dax</div>
          <div className="bg-[#0d0b0a] border border-[#2c2520] rounded p-3 min-h-[60px]">
            <pre className="text-xs text-[#968a80] font-mono leading-relaxed whitespace-pre-wrap select-all">{metric.powerBi.code}</pre>
            
            <div className="mt-3 pt-2 border-t border-[#1c1715] text-[9px] text-[#69615a] flex gap-4 font-mono select-none">
              <div>
                <span className="font-bold">reads tables</span>
                <span className="block text-[#c95f5f] font-semibold mt-0.5">{metric.powerBi.readsTables.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">reads columns</span>
                <span className="block text-[#968a80] mt-0.5">{metric.powerBi.readsColumns.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">aggregates</span>
                <span className="block text-[#968a80] mt-0.5">{metric.powerBi.aggregates.join(', ')}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Warehouse panel */}
        <div className="space-y-1">
          <div className="text-[8px] font-semibold text-[#69615a] uppercase">WAREHOUSE sql</div>
          <div className="bg-[#0d0b0a] border border-[#2c2520] rounded p-3 min-h-[60px]">
            <pre className="text-xs text-[#968a80] font-mono leading-relaxed whitespace-pre-wrap select-all">{metric.warehouse.code}</pre>
            
            <div className="mt-3 pt-2 border-t border-[#1c1715] text-[9px] text-[#69615a] flex gap-4 font-mono select-none">
              <div>
                <span className="font-bold">reads tables</span>
                <span className="block text-[#c95f5f] font-semibold mt-0.5">{metric.warehouse.readsTables.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">reads columns</span>
                <span className="block text-[#968a80] mt-0.5">{metric.warehouse.readsColumns.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">aggregates</span>
                <span className="block text-[#968a80] mt-0.5">{metric.warehouse.aggregates.join(', ')}</span>
              </div>
            </div>
          </div>
        </div>

      </div>

      <div className="text-[10px] text-[#69615a] pt-1.5 font-mono select-text">
        {metric.callout}
      </div>

    </div>
  );
}

export default App;
