import { useState, useRef, useEffect } from 'react';
import {
  ChevronDown,
  Sparkles,
  Search,
  Database,
  AlertTriangle,
  Copy,
  Workflow
} from 'lucide-react';
import {
  OVERVIEW_STATS,
  UNRESOLVED_SECTION,
  AWAITING_CONFIRMATION,
  TABLES_TREE,
  OBJECT_DETAILS,
  REQUIREMENTS,
  RECONCILE_METRICS,
  RECONCILE_ONLY_POWERBI,
  RECONCILE_ONLY_WAREHOUSE,
  REVIEW_QUEUE,
  COPILOT_RESPONSES,
  DRIFT_STATS,
  DRIFT_ITEMS,
  type ModelObject
} from './mockData';

function App() {
  const [activeScreen, setActiveScreen] = useState<'overview' | 'model' | 'requirements' | 'drift' | 'reconcile' | 'review'>('model');
  const [isCopilotOpen, setIsCopilotOpen] = useState(true);
  
  // Model Screen state
  const [modelSearch, setModelSearch] = useState('');
  const [expandedTables, setExpandedTables] = useState<Record<string, boolean>>({
    'QC Metrics': true,
    'TestResult': true
  });
  const [selectedObject, setSelectedObject] = useState<ModelObject | null>(null);

  // Requirements screen state
  const [expandedRequirements, setExpandedRequirements] = useState<Record<string, boolean>>({});
  const [reqFilter, setReqFilter] = useState<'all' | 'high' | 'medium' | 'low'>('all');
  const [reqDocType, setReqDocType] = useState<'BRD' | 'FRD'>('BRD');

  // Copilot interactive state
  const [copilotInput, setCopilotInput] = useState('');
  const [chatLog, setChatLog] = useState<{ sender: 'user' | 'copilot'; text: string; isThinking?: boolean }[]>([]);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Review copy state
  const [copiedQueue, setCopiedQueue] = useState(false);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatLog]);

  const toggleTableExpand = (tableName: string) => {
    setExpandedTables(prev => ({
      ...prev,
      [tableName]: !prev[tableName]
    }));
  };

  const handleObjectSelect = (name: string, tableName: string, type: 'column' | 'measure') => {
    if (OBJECT_DETAILS[name]) {
      setSelectedObject(OBJECT_DETAILS[name]);
    } else {
      const basicDetail: ModelObject = {
        id: `${type}:${tableName}.${name}`,
        name,
        type,
        tableName,
        description: `Autogenerated schema documentation for ${tableName}[${name}].`,
        upstream: [],
        downstream: [
          { name: `Join: ${tableName} -> TestResult`, type: 'table', path: 'TestResult' }
        ],
        fingerprint: `sha256:${Math.random().toString(16).substring(2, 10)}b8ac${Math.random().toString(16).substring(2, 6)}df09`
      };
      setSelectedObject(basicDetail);
    }
  };

  const handleCopilotSubmit = (text: string) => {
    if (!text.trim()) return;
    const cleanText = text.toLowerCase().trim();
    
    // Add user message
    const newLog = [...chatLog, { sender: 'user' as const, text }];
    setChatLog(newLog);
    setCopilotInput('');

    // Add thinking state
    setChatLog(prev => [...prev, { sender: 'copilot', text: 'Analyzing semantic graph...', isThinking: true }]);

    setTimeout(() => {
      let reply = "I couldn't find a direct correlation in the current semantic graph. Try asking: \"What does OOS Rate measure?\" or \"What breaks if I change Tests Performed?\" or \"Which joins are inactive?\"";
      
      // Robust keyword matching to support typos, singulars/plurals, and partial questions
      if (cleanText.includes('oos') || cleanText.includes('out of spec') || cleanText.includes('out-of-spec')) {
        reply = COPILOT_RESPONSES["what does oos rate measure?"];
      } else if (cleanText.includes('performed') || (cleanText.includes('tests') && cleanText.includes('break')) || (cleanText.includes('change') && cleanText.includes('tests'))) {
        reply = COPILOT_RESPONSES["what breaks if i change tests performed?"];
      } else if ((cleanText.includes('how many') || cleanText.includes('number of') || cleanText.includes('count')) && cleanText.includes('join')) {
        reply = "Checking extraction metadata...\n\nThere are **6 joins** (relationships) defined in the QualityControl semantic model connecting your 6 user tables.";
      } else if (cleanText.includes('inactive') || (cleanText.includes('join') && cleanText.includes('inactive')) || cleanText.includes('which joins') || cleanText.includes('which join')) {
        reply = COPILOT_RESPONSES["which joins are inactive?"];
      } else if (cleanText.includes('join') || cleanText.includes('relationship') || cleanText.includes('connect')) {
        reply = "There are **6 joins** extracted in total. All of them are active, except for the relationship pathway between `Batch` and `Calendar` which is marked inactive (REQ-B-58c38b).";
      }

      setChatLog(prev => {
        const filtered = prev.filter(item => !item.isThinking);
        return [...filtered, { sender: 'copilot' as const, text: reply }];
      });
    }, 700);
  };

  const handleCopyQueue = () => {
    const queueText = JSON.stringify(REVIEW_QUEUE, null, 2);
    navigator.clipboard.writeText(queueText).then(() => {
      setCopiedQueue(true);
      setTimeout(() => setCopiedQueue(false), 2000);
    });
  };

  const toggleReqExpand = (reqId: string) => {
    setExpandedRequirements(prev => ({
      ...prev,
      [reqId]: !prev[reqId]
    }));
  };

  // Filter requirements based on confidence badge selection
  const filteredRequirements = REQUIREMENTS.filter(req => {
    if (reqFilter === 'all') return true;
    return req.confidence.toLowerCase() === reqFilter;
  });

  return (
    <div className="min-h-screen flex flex-col font-mono text-xs overflow-hidden select-none bg-bg-primary text-text-primary">
      
      {/* GLOBAL TOP-MOST BAR */}
      <header className="h-10 border-b border-border-subtle px-4 flex items-center justify-between shrink-0 bg-bg-tertiary">
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1.5 text-accent-gold hover:opacity-85 cursor-pointer">
            <span className="font-bold text-xs tracking-wider">Concordance — semantic layer interface</span>
            <ChevronDown size={11} className="text-text-secondary" />
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="w-6 h-6 rounded-full bg-[#5d3ab7] text-white flex items-center justify-center font-bold text-[10px] cursor-pointer" title="User Profile">
            AP
          </div>
          <button className="text-[10px] text-text-secondary hover:text-text-primary bg-bg-secondary border border-border-subtle px-2 py-0.5 rounded">
            Share
          </button>
        </div>
      </header>

      {/* SECONDARY SUB-HEADER BAR */}
      <div className="h-11 border-b border-border-subtle px-4 flex items-center justify-between bg-bg-tertiary shrink-0">
        <div className="flex items-center gap-1.5 text-xs">
          <span className="text-text-secondary">Concordance</span>
          <span className="text-border-subtle">|</span>
          <span className="text-text-primary font-bold">QualityControl</span>
        </div>

        <div className="flex items-center gap-3">
          <span className="text-text-secondary text-[10px]">20 measures · 6 joins</span>
          
          <button 
            onClick={() => setIsCopilotOpen(!isCopilotOpen)}
            className={`flex items-center gap-1 px-2.5 py-0.5 rounded border text-[10px] transition-all font-semibold ${isCopilotOpen ? 'bg-brand-green-bg border-brand-green-border text-brand-green-text' : 'bg-bg-secondary border-border-subtle text-text-secondary'}`}
          >
            <Sparkles size={10} />
            <span>copilot</span>
          </button>
        </div>
      </div>

      {/* BODY WORKSPACE */}
      <div className="flex-1 flex overflow-hidden">
        
        {/* SIDEBAR NAVIGATION */}
        <nav className="w-[150px] border-r border-border-subtle bg-bg-tertiary flex flex-col justify-between shrink-0 p-3">
          <div className="space-y-1">
            {[
              { id: 'overview', label: 'Overview' },
              { id: 'model', label: 'Model' },
              { id: 'requirements', label: 'Requirements' },
              { id: 'drift', label: 'Drift' },
              { id: 'reconcile', label: 'Reconcile' },
              { id: 'review', label: 'Review' }
            ].map(item => {
              const active = activeScreen === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => setActiveScreen(item.id as any)}
                  className={`w-full text-left px-2 py-1.5 rounded transition-all text-xs ${active ? 'bg-bg-secondary text-accent-gold font-bold border-l-2 border-accent-gold' : 'text-text-secondary hover:text-text-primary hover:bg-bg-secondary'}`}
                >
                  {item.label}
                </button>
              );
            })}
          </div>

          <div className="p-2 bg-bg-secondary rounded border border-border-subtle text-[8px] text-text-secondary space-y-0.5">
            <div>ENGINE: <span className="text-text-primary">tmdl-v2</span></div>
            <div>VER: <span className="text-text-primary">0.42.1</span></div>
          </div>
        </nav>

        {/* MAIN PANEL CONTENT */}
        <main className="flex-1 overflow-y-auto bg-bg-primary flex flex-col p-6 min-w-0 select-text">
          
          {/* SCREEN 1: OVERVIEW */}
          {activeScreen === 'overview' && (
            <div className="space-y-6 max-w-5xl">
              <div>
                <h1 className="text-lg font-bold text-text-primary tracking-wide">QualityControl</h1>
                <p className="text-text-secondary mt-0.5 text-xs">tmdl · 6 user tables of {OVERVIEW_STATS.tables}</p>
              </div>

              {/* 6 Stats row */}
              <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
                {[
                  { label: 'TABLES', val: OVERVIEW_STATS.tables },
                  { label: 'COLUMNS', val: OVERVIEW_STATS.columns },
                  { label: 'MEASURES', val: OVERVIEW_STATS.measures },
                  { label: 'JOINS', val: OVERVIEW_STATS.joins },
                  { label: 'HIERARCHIES', val: OVERVIEW_STATS.hierarchies },
                  { label: 'NEEDS REVIEW', val: OVERVIEW_STATS.needsReview, alert: true }
                ].map((stat, i) => (
                  <div key={i} className="p-3 bg-bg-panel border border-border-subtle rounded flex flex-col justify-between min-h-[70px]">
                    <div className="text-[9px] text-text-secondary tracking-wider font-semibold uppercase">{stat.label}</div>
                    <div className={`text-xl font-bold mt-1 tabular-nums ${stat.alert ? 'text-accent-gold' : 'text-text-primary'}`}>
                      {stat.val}
                    </div>
                  </div>
                ))}
              </div>

              {/* Warnings panel */}
              <div className="p-4 bg-bg-panel border border-border-subtle rounded space-y-2">
                <div className="text-[9px] text-text-secondary tracking-wider uppercase font-bold">WHAT WAS NOT READ OR RESOLVED</div>
                <div className="text-xs text-text-secondary bg-bg-code p-3 rounded border border-border-subtle font-mono leading-relaxed">
                  {UNRESOLVED_SECTION.warningText}
                </div>
              </div>

              {/* Awaiting Confirmation (low confidence) */}
              <div className="space-y-3">
                <div className="text-[9px] text-text-secondary tracking-wider uppercase font-bold">AWAITING CONFIRMATION ({AWAITING_CONFIRMATION.length})</div>
                
                <div className="space-y-2">
                  {AWAITING_CONFIRMATION.map(item => (
                    <div key={item.id} className="p-4 bg-bg-panel border border-border-subtle rounded flex flex-col gap-2">
                      <div className="flex items-center gap-2">
                        <span className="text-brand-red-text font-bold text-xs">{item.id}</span>
                        <span className="text-[8px] bg-brand-red-bg text-brand-red-text px-1 py-0.2 rounded border border-brand-red-border font-semibold uppercase">low</span>
                        <span className="text-[8px] bg-bg-secondary text-text-secondary px-1.5 py-0.2 rounded border border-border-subtle">{item.rule}</span>
                      </div>
                      <div className="text-xs text-text-secondary leading-relaxed" dangerouslySetInnerHTML={{ __html: item.textHtml }} />
                      <div className="text-[11px] text-text-secondary italic">{item.explanation}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Footer */}
              <div className="pt-6 border-t border-border-subtle text-text-secondary flex items-center justify-between text-[10px]">
                <span>drift not configured · reconcile configured</span>
              </div>
            </div>
          )}

          {/* SCREEN 2: MODEL */}
          {activeScreen === 'model' && (
            <div className="flex-1 flex flex-col md:flex-row gap-5 min-h-0">
              
              {/* Expandable Object Tree */}
              <div className="w-full md:w-[260px] flex flex-col bg-bg-panel border border-border-subtle rounded min-h-0 shrink-0">
                <div className="p-3 border-b border-border-subtle space-y-2">
                  <div className="relative">
                    <Search className="absolute left-2 top-2 text-text-secondary" size={11} />
                    <input
                      type="text"
                      placeholder="Filter objects"
                      value={modelSearch}
                      onChange={(e) => setModelSearch(e.target.value)}
                      className="w-full bg-bg-code border border-border-subtle rounded pl-7 pr-2.5 py-1 text-xs text-text-primary focus:outline-none focus:border-accent-gold placeholder-text-secondary font-mono"
                    />
                  </div>
                </div>

                <div className="flex-1 overflow-y-auto p-2 space-y-1">
                  {TABLES_TREE.map(table => {
                    const isExpanded = !!expandedTables[table.name];
                    const filteredChildren = table.children.filter(child => 
                      child.name.toLowerCase().includes(modelSearch.toLowerCase()) ||
                      table.name.toLowerCase().includes(modelSearch.toLowerCase())
                    );

                    if (modelSearch && filteredChildren.length === 0 && !table.name.toLowerCase().includes(modelSearch.toLowerCase())) {
                      return null;
                    }

                    return (
                      <div key={table.name} className="space-y-0.5">
                        <button
                          onClick={() => toggleTableExpand(table.name)}
                          className="w-full flex items-center justify-between p-1 rounded hover:bg-bg-secondary text-text-secondary hover:text-text-primary"
                        >
                          <div className="flex items-center gap-1">
                            <span className="text-[10px] font-mono text-text-secondary w-3 text-center">
                              {isExpanded ? '−' : '+'}
                            </span>
                            <span className={`font-semibold ${table.hasMeasures ? 'text-accent-gold' : 'text-text-primary'}`}>
                              {table.name}
                            </span>
                            {table.hasMeasures && (
                              <span className="text-[8px] text-brand-green-text bg-brand-green-bg border border-brand-green-border px-1 rounded ml-1 scale-90">
                                fx
                              </span>
                            )}
                          </div>
                          <span className="text-[9px] text-text-secondary font-mono">{table.childCount}</span>
                        </button>

                        {isExpanded && (
                          <div className="pl-4 border-l border-border-subtle ml-2.5 space-y-0.5">
                            {filteredChildren.map(child => {
                              const isSelected = selectedObject?.name === child.name && selectedObject?.tableName === table.name;
                              return (
                                <button
                                  key={child.name}
                                  onClick={() => handleObjectSelect(child.name, table.name, child.type)}
                                  className={`w-full flex items-center justify-between px-2 py-0.5 rounded text-left ${
                                    isSelected 
                                      ? 'bg-bg-secondary text-accent-gold border-l-2 border-accent-gold' 
                                      : 'text-text-secondary hover:text-text-primary'
                                  }`}
                                >
                                  <span className="truncate">{child.name}</span>
                                  <span className="text-[7px] opacity-40 select-none">{child.type.substring(0, 3)}</span>
                                </button>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
                
                <div className="p-2 border-t border-border-subtle bg-bg-code text-text-secondary text-[8px] text-center font-mono">
                  68 objects · 121 edges
                </div>
              </div>

              {/* Right Detail Pane */}
              <div className="flex-1 flex flex-col bg-bg-panel border border-border-subtle rounded min-w-0">
                {selectedObject ? (
                  <div className="flex-1 flex flex-col min-h-0 overflow-y-auto p-5 space-y-5">
                    
                    {/* Header */}
                    <div className="border-b border-border-subtle pb-4 flex flex-col sm:flex-row justify-between sm:items-center gap-3">
                      <div>
                        <div className="flex items-center gap-1.5">
                          <span className={`text-[8px] px-1 py-0.2 rounded border font-semibold ${selectedObject.type === 'measure' ? 'bg-brand-green-bg border-brand-green-border text-brand-green-text' : 'bg-bg-secondary border-border-subtle text-accent-gold'}`}>
                            {selectedObject.type.toUpperCase()}
                          </span>
                          <span className="text-text-secondary text-xs font-bold">{selectedObject.tableName}</span>
                        </div>
                        <h2 className="text-base font-bold text-accent-gold mt-1">{selectedObject.name}</h2>
                      </div>
                      <div className="text-right">
                        <span className="text-[9px] text-text-secondary font-mono block">SHA-256 FINGERPRINT</span>
                        <code className="text-[9px] text-text-secondary select-all bg-bg-code px-1.5 py-0.5 rounded border border-border-subtle font-mono block mt-1 truncate max-w-[240px]">
                          {selectedObject.fingerprint}
                        </code>
                      </div>
                    </div>

                    {/* Description */}
                    {selectedObject.description && (
                      <div className="space-y-1.5">
                        <div className="text-[9px] text-text-secondary uppercase tracking-wider font-bold">Description</div>
                        <p className="text-xs text-text-primary bg-bg-code p-3 rounded border border-border-subtle leading-relaxed">
                          {selectedObject.description}
                        </p>
                      </div>
                    )}

                    {/* DAX Formula */}
                    {selectedObject.type === 'measure' && selectedObject.formula && (
                      <div className="space-y-1.5">
                        <span className="text-[9px] text-text-secondary uppercase tracking-wider font-bold">DAX expression</span>
                        <div className="bg-bg-code border border-border-subtle rounded p-3 overflow-x-auto">
                          <pre className="text-xs text-accent-gold leading-5 whitespace-pre">
                            {selectedObject.cleanedFormula}
                          </pre>
                        </div>
                      </div>
                    )}

                    {/* Dependencies Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                      
                      <div className="border border-border-subtle rounded bg-bg-code p-4 space-y-3">
                        <div className="flex items-center gap-2 border-b border-border-subtle pb-2">
                          <Workflow size={11} className="text-text-secondary" />
                          <span className="text-[9px] font-bold text-text-primary uppercase tracking-wider">Upstream Dependencies ({selectedObject.upstream.length})</span>
                        </div>
                        {selectedObject.upstream.length > 0 ? (
                          <div className="space-y-1">
                            {selectedObject.upstream.map((dep, index) => (
                              <div key={index} className="flex items-center justify-between text-xs py-1 px-2 bg-bg-panel rounded border border-border-subtle">
                                <span className="text-text-primary">{dep.name}</span>
                                <span className="text-[8px] bg-bg-secondary border border-border-subtle px-1 rounded text-accent-gold">{dep.type}</span>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <div className="text-xs text-text-secondary italic">No upstream semantic layers detected.</div>
                        )}
                      </div>

                      <div className="border border-border-subtle rounded bg-bg-code p-4 space-y-3">
                        <div className="flex items-center gap-2 border-b border-border-subtle pb-2">
                          <AlertTriangle size={11} className="text-brand-red-text" />
                          <span className="text-[9px] font-bold text-brand-red-text uppercase tracking-wider">Breakage Downstream ({selectedObject.downstream.length})</span>
                        </div>
                        {selectedObject.downstream.length > 0 ? (
                          <div className="space-y-1">
                            {selectedObject.downstream.map((dep, index) => (
                              <div key={index} className="flex items-center justify-between text-xs py-1 px-2 bg-brand-red-bg/50 rounded border border-brand-red-border">
                                <span className="text-brand-red-text font-semibold">{dep.name}</span>
                                <span className="text-[8px] bg-brand-red-bg border border-brand-red-border px-1 rounded text-brand-red-text">{dep.type}</span>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <div className="text-xs text-text-secondary italic">No downstream dependencies breakages mapped.</div>
                        )}
                      </div>

                    </div>

                  </div>
                ) : (
                  <div className="flex-1 flex items-center justify-center text-center p-8">
                    <div className="space-y-2">
                      <Database size={24} className="text-border-subtle mx-auto" />
                      <div className="text-xs text-text-secondary">Select an object to see how it is defined and what depends on it.</div>
                    </div>
                  </div>
                )}
                
                <div className="p-3 border-t border-border-subtle text-text-secondary text-[9px] flex items-center justify-between bg-bg-secondary">
                  <span>Source TMDL: C:\git\QualityControl\QC_Metrics.tmdl</span>
                  <span>Extracted: 2026-08-24 16:15:31</span>
                </div>
              </div>

            </div>
          )}

          {/* SCREEN 3: REQUIREMENTS */}
          {activeScreen === 'requirements' && (
            <div className="space-y-6 max-w-5xl">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h1 className="text-lg font-bold text-text-primary tracking-wide">Business requirements</h1>
                  <p className="text-text-secondary mt-0.5 text-xs">Derived from the model by code, not written by a language model.</p>
                </div>

                {/* BRD/FRD tab selection */}
                <div className="flex bg-bg-panel border border-border-subtle rounded p-0.5 select-none shrink-0 font-mono text-[9px] font-semibold">
                  <button
                    onClick={() => setReqDocType('BRD')}
                    className={`px-2 py-0.5 rounded transition-all ${reqDocType === 'BRD' ? 'bg-brand-green-bg border border-brand-green-border text-brand-green-text' : 'text-text-secondary hover:text-text-primary'}`}
                  >
                    BRD
                  </button>
                  <button
                    onClick={() => setReqDocType('FRD')}
                    className={`px-2 py-0.5 rounded transition-all ${reqDocType === 'FRD' ? 'bg-brand-green-bg border border-brand-green-border text-brand-green-text' : 'text-text-secondary hover:text-text-primary'}`}
                  >
                    FRD
                  </button>
                </div>
              </div>

              {/* Requirement statistics */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { label: 'REQUIREMENTS', val: 31 },
                  { label: 'STATED BY THE MODEL', val: 25 },
                  { label: 'FROM A STRUCTURAL RULE', val: 5 },
                  { label: 'INFERRED - NEEDS A PERSON', val: 1, alert: true }
                ].map((stat, i) => (
                  <div key={i} className="p-3 bg-bg-panel border border-border-subtle rounded flex flex-col justify-between min-h-[65px]">
                    <div className="text-[8px] text-text-secondary tracking-wider uppercase font-semibold">{stat.label}</div>
                    <div className={`text-xl font-bold mt-1 ${stat.alert ? 'text-brand-red-text' : 'text-text-primary'}`}>
                      {stat.val}
                    </div>
                  </div>
                ))}
              </div>

              {/* Show Filters */}
              <div className="flex items-center gap-2 text-[9px] font-semibold">
                <span className="text-text-secondary uppercase">SHOW</span>
                <div className="flex border border-border-subtle rounded p-0.5 bg-bg-panel">
                  {(['all', 'high', 'medium', 'low'] as const).map(f => (
                    <button
                      key={f}
                      onClick={() => setReqFilter(f)}
                      className={`px-2 py-0.5 rounded uppercase ${reqFilter === f ? 'bg-bg-secondary text-accent-gold font-bold' : 'text-text-secondary hover:text-text-primary'}`}
                    >
                      {f}
                    </button>
                  ))}
                </div>
              </div>

              {/* Cards List */}
              <div className="space-y-3">
                {filteredRequirements.map(req => {
                  const isExpanded = !!expandedRequirements[req.id];
                  return (
                    <div key={req.id} className="bg-bg-panel border border-border-subtle rounded hover:border-bg-secondary transition-all">
                      <div className="p-4 flex flex-col sm:flex-row justify-between items-start gap-4">
                        <div className="space-y-1.5">
                          <div className="flex items-center gap-2">
                            <span className="font-bold text-accent-gold">{req.id}</span>
                            <span className="text-[8px] bg-bg-secondary border border-border-subtle text-text-secondary px-1.5 py-0.2 rounded font-mono">
                              {req.rule}
                            </span>
                          </div>
                          <div className="text-xs text-text-primary leading-relaxed" dangerouslySetInnerHTML={{ __html: req.textHtml }} />
                          <p className="text-[11px] text-text-secondary italic">{req.explanation}</p>
                        </div>

                        <div className="shrink-0 text-right">
                          <span className={`inline-block text-[8px] font-bold px-2 py-0.5 rounded border ${
                            req.confidence === 'HIGH' ? 'bg-brand-green-bg border-brand-green-border text-brand-green-text' : 
                            req.confidence === 'MEDIUM' ? 'bg-brand-yellow-bg border-brand-yellow-border text-brand-yellow-text' : 
                            'bg-brand-red-bg border-brand-red-border text-brand-red-text'
                          }`}>
                            {req.confidence.toLowerCase()}
                          </span>
                        </div>
                      </div>

                      {/* Expandable footers */}
                      <div className="border-t border-border-subtle bg-bg-secondary">
                        <button
                          onClick={() => toggleReqExpand(req.id)}
                          className="w-full flex items-center justify-between px-4 py-1.5 text-text-secondary hover:text-text-primary text-[9px]"
                        >
                          <span className="font-semibold">
                            {isExpanded ? '−' : '+'} bound to {req.boundObjects.length} object
                          </span>
                        </button>
                        {isExpanded && (
                          <div className="px-6 py-2 border-t border-border-subtle bg-bg-code space-y-1 font-mono text-[10px] text-text-secondary">
                            {req.boundObjects.map((obj, idx) => (
                              <div key={idx} className="hover:underline cursor-pointer" onClick={() => {
                                setActiveScreen('model');
                                const base = obj.split('.').pop() || obj;
                                const tab = obj.split('.')[0] || '';
                                handleObjectSelect(base, tab, 'column');
                              }}>
                                {obj}
                              </div>
                            ))}
                          </div>
                        )}
                      </div>

                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* SCREEN 4: DRIFT */}
          {activeScreen === 'drift' && (
            <div className="space-y-6 max-w-5xl">
              <div>
                <h1 className="text-lg font-bold text-text-primary tracking-wide">Drift analysis</h1>
                <p className="text-text-secondary mt-0.5 text-xs">Compare model baseline snapshot against active local extraction TMDL files.</p>
              </div>

              {/* Stats Row */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { label: 'DETECTED CHANGES', val: DRIFT_STATS.detectedChanges },
                  { label: 'REAL LOGIC CHANGES', val: DRIFT_STATS.logicChanges },
                  { label: 'HARMLESS RENAMES', val: DRIFT_STATS.renames },
                  { label: 'STALE DOCUMENTS', val: DRIFT_STATS.staleDocs, alert: true }
                ].map((stat, i) => (
                  <div key={i} className="p-3 bg-bg-panel border border-border-subtle rounded flex flex-col justify-between min-h-[65px]">
                    <div className="text-[8px] text-text-secondary tracking-wider uppercase font-semibold">{stat.label}</div>
                    <div className={`text-xl font-bold mt-1 ${stat.alert ? 'text-accent-gold' : 'text-text-primary'}`}>
                      {stat.val}
                    </div>
                  </div>
                ))}
              </div>

              {/* Real Logic Changes List */}
              <div className="space-y-3">
                <div className="text-[9px] text-text-secondary uppercase font-bold tracking-wider">
                  Real Logic Changes — logic fingerprints mismatched (1)
                </div>
                
                {DRIFT_ITEMS.filter(item => item.type === 'logic').map(item => (
                  <div key={item.name} className="bg-bg-panel border border-border-subtle rounded p-4 space-y-3">
                    <div className="flex justify-between items-start gap-4 border-b border-border-subtle pb-2">
                      <div>
                        <h3 className="font-bold text-xs text-brand-red-text">{item.name}</h3>
                        <span className="text-[8px] bg-brand-red-bg text-brand-red-text border border-brand-red-border px-1.5 py-0.2 rounded font-semibold uppercase mt-1 inline-block">
                          {item.status}
                        </span>
                      </div>
                      <div className="text-right space-y-1">
                        <div>
                          <span className="text-[8px] text-text-secondary font-mono block">OLD SHA-256</span>
                          <code className="text-[8px] text-text-secondary bg-bg-code px-1.5 py-0.2 rounded border border-border-subtle font-mono truncate max-w-[200px] inline-block">{item.oldFingerprint}</code>
                        </div>
                        <div>
                          <span className="text-[8px] text-text-secondary font-mono block">NEW SHA-256</span>
                          <code className="text-[8px] text-brand-red-text bg-brand-red-bg px-1.5 py-0.2 rounded border border-brand-red-border font-mono truncate max-w-[200px] inline-block">{item.newFingerprint}</code>
                        </div>
                      </div>
                    </div>

                    {/* Code Diff Side by Side */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div>
                        <div className="text-[8px] text-text-secondary uppercase font-semibold mb-1">Baseline Code</div>
                        <div className="bg-bg-code border border-border-subtle rounded p-3 text-xs text-text-secondary overflow-x-auto whitespace-pre font-mono">
                          {item.oldCode}
                        </div>
                      </div>
                      <div>
                        <div className="text-[8px] text-text-secondary uppercase font-semibold mb-1">New Code</div>
                        <div className="bg-bg-code border border-brand-red-border rounded p-3 text-xs text-brand-red-text overflow-x-auto whitespace-pre font-mono">
                          {item.newCode}
                        </div>
                      </div>
                    </div>

                    {/* Stale requirements mapped */}
                    <div className="pt-2 border-t border-border-subtle text-[10px] text-text-secondary space-y-1">
                      <div className="font-bold uppercase text-[8px] text-text-secondary">Impacted Documentation:</div>
                      {item.affectedRequirements.map(req => (
                        <div key={req.id} className="flex items-center gap-2">
                          <span className="font-mono text-accent-gold underline cursor-pointer" onClick={() => {
                            setActiveScreen('requirements');
                            setReqFilter('all');
                          }}>{req.id}</span>
                          <span className="text-[8px] bg-brand-red-bg border border-brand-red-border text-brand-red-text px-1 py-0.2 rounded uppercase font-semibold">
                            stale — logic modified (requires re-verification)
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>

              {/* Harmless Renames List */}
              <div className="space-y-3">
                <div className="text-[9px] text-text-secondary uppercase font-bold tracking-wider">
                  Harmless Renames — logic identical, names modified (1)
                </div>
                
                {DRIFT_ITEMS.filter(item => item.type === 'rename').map(item => (
                  <div key={item.name} className="bg-bg-panel border border-border-subtle rounded p-4 space-y-3">
                    <div className="flex justify-between items-start gap-4 border-b border-border-subtle pb-2">
                      <div>
                        <h3 className="font-bold text-xs text-brand-green-text">{item.name}</h3>
                        <span className="text-[8px] bg-brand-green-bg text-brand-green-text border border-brand-green-border px-1.5 py-0.2 rounded font-semibold uppercase mt-1 inline-block">
                          {item.status}
                        </span>
                      </div>
                      <div className="text-right">
                        <span className="text-[8px] text-text-secondary font-mono block">IDENTICAL SHA-256 FINGERPRINT</span>
                        <code className="text-[8px] text-text-secondary bg-bg-code px-1.5 py-0.2 rounded border border-border-subtle font-mono truncate max-w-[240px] inline-block">{item.fingerprint}</code>
                      </div>
                    </div>

                    {/* Code comparison side-by-side */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div>
                        <div className="text-[8px] text-text-secondary uppercase font-semibold mb-1">Old Definition</div>
                        <div className="bg-bg-code border border-border-subtle rounded p-3 text-xs text-text-secondary overflow-x-auto whitespace-pre font-mono">
                          {item.oldCode}
                        </div>
                      </div>
                      <div>
                        <div className="text-[8px] text-text-secondary uppercase font-semibold mb-1">New Definition</div>
                        <div className="bg-bg-code border border-border-subtle rounded p-3 text-xs text-text-secondary overflow-x-auto whitespace-pre font-mono">
                          {item.newCode}
                        </div>
                      </div>
                    </div>

                    {/* Stale requirements mapped */}
                    <div className="pt-2 border-t border-border-subtle text-[10px] text-text-secondary space-y-1">
                      <div className="font-bold uppercase text-[8px] text-text-secondary">Impacted Documentation:</div>
                      {item.affectedRequirements.map(req => (
                        <div key={req.id} className="flex items-center gap-2">
                          <span className="font-mono text-accent-gold underline cursor-pointer" onClick={() => {
                            setActiveScreen('requirements');
                            setReqFilter('all');
                          }}>{req.id}</span>
                          <span className="text-[8px] bg-brand-yellow-bg border border-brand-yellow-border text-brand-yellow-text px-1 py-0.2 rounded uppercase font-semibold">
                            safe — rename only (update text labels only)
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>

            </div>
          )}

          {/* SCREEN 5: RECONCILE */}
          {activeScreen === 'reconcile' && (
            <div className="space-y-6 max-w-6xl">
              <div>
                <h1 className="text-lg font-bold text-text-primary tracking-wide">Cross-platform reconciliation</h1>
                <p className="text-text-secondary mt-0.5 text-xs">QualityControl against quality_control.duckdb</p>
              </div>

              {/* 4 reconciliation stat cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { label: 'DEFINED ON BOTH', val: 6, border: 'border-border-subtle text-text-primary' },
                  { label: 'DIVERGENT', val: 1, border: 'border-brand-red-border text-brand-red-text' },
                  { label: 'NEEDS REVIEW', val: 1, border: 'border-brand-yellow-border text-brand-yellow-text' },
                  { label: 'CONSISTENT', val: 4, border: 'border-brand-green-border text-brand-green-text' }
                ].map((stat, i) => (
                  <div key={i} className={`p-3 bg-bg-panel border rounded flex flex-col justify-between min-h-[65px] ${stat.border}`}>
                    <div className="text-[8px] text-text-secondary tracking-wider uppercase font-semibold">{stat.label}</div>
                    <div className="text-xl font-bold mt-1 tabular-nums">{stat.val}</div>
                  </div>
                ))}
              </div>

              {/* Divergent section */}
              <div className="space-y-3">
                <div className="text-[9px] text-text-secondary uppercase font-bold tracking-wider pb-1">
                  Divergent — these will report different numbers (1)
                </div>
                {RECONCILE_METRICS.filter(m => m.status === 'divergent').map(metric => (
                  <ReconcileMetricRow key={metric.name} metric={metric} />
                ))}
              </div>

              {/* Needs review section */}
              <div className="space-y-3">
                <div className="text-[9px] text-text-secondary uppercase font-bold tracking-wider pb-1">
                  Needs review — differs, but may still agree (1)
                </div>
                {RECONCILE_METRICS.filter(m => m.status === 'needs review').map(metric => (
                  <ReconcileMetricRow key={metric.name} metric={metric} />
                ))}
              </div>

              {/* Consistent section */}
              <div className="space-y-3">
                {RECONCILE_METRICS.filter(m => m.status === 'consistent').map(metric => (
                  <ReconcileMetricRow key={metric.name} metric={metric} />
                ))}
              </div>

              {/* Only In lists columns */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-border-subtle pt-5">
                
                <div className="bg-bg-panel border border-border-subtle rounded p-4">
                  <div className="text-[9px] font-bold text-accent-gold uppercase border-b border-border-subtle pb-2 mb-2 tracking-wider">
                    ONLY IN POWER_BI ({RECONCILE_ONLY_POWERBI.length})
                  </div>
                  <div className="space-y-1 overflow-y-auto max-h-[250px] pr-2">
                    {RECONCILE_ONLY_POWERBI.map(item => (
                      <div key={item} className="text-xs text-text-secondary py-1 border-b border-bg-primary font-semibold">
                        {item}
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-bg-panel border border-border-subtle rounded p-4">
                  <div className="text-[9px] font-bold text-text-secondary uppercase border-b border-border-subtle pb-2 mb-2 tracking-wider">
                    ONLY IN WAREHOUSE ({RECONCILE_ONLY_WAREHOUSE.length})
                  </div>
                  <div className="space-y-1">
                    {RECONCILE_ONLY_WAREHOUSE.map(item => (
                      <div key={item} className="text-xs text-text-secondary py-1 border-b border-bg-primary font-mono">
                        {item}
                      </div>
                    ))}
                  </div>
                </div>

              </div>

            </div>
          )}

          {/* SCREEN 5: REVIEW */}
          {activeScreen === 'review' && (
            <div className="space-y-6 max-w-4xl">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h1 className="text-lg font-bold text-text-primary tracking-wide">Awaiting confirmation</h1>
                  <p className="text-text-secondary mt-0.5 text-xs">Review low-confidence inferred items needing human confirmation.</p>
                </div>
                
                <button
                  onClick={handleCopyQueue}
                  className="flex items-center gap-1.5 px-3 py-1 bg-bg-secondary border border-accent-gold text-accent-gold font-bold rounded hover:opacity-85 cursor-pointer"
                >
                  <Copy size={11} />
                  <span>{copiedQueue ? 'COPIED!' : 'COPY THE QUEUE'}</span>
                </button>
              </div>

              <div className="space-y-3">
                {REVIEW_QUEUE.map(item => (
                  <div key={item.id} className="bg-bg-panel border border-border-subtle rounded p-4 space-y-3">
                    <div className="flex justify-between items-center border-b border-border-subtle pb-2">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-xs text-accent-gold">{item.id}</span>
                        <span className="text-[8px] bg-brand-red-bg text-brand-red-text px-1.5 py-0.2 rounded border border-brand-red-border font-semibold">REVIEW</span>
                      </div>
                      <span className="text-[9px] text-text-secondary uppercase font-bold">{item.rule}</span>
                    </div>

                    <div className="space-y-2">
                      <div className="text-xs text-text-primary leading-relaxed" dangerouslySetInnerHTML={{ __html: item.textHtml }} />
                      <div className="text-[11px] text-text-secondary bg-bg-code p-3 rounded border border-border-subtle font-mono leading-relaxed">
                        {item.explanation}
                      </div>
                    </div>

                    <div className="flex justify-between items-center text-[10px] pt-1.5 text-text-secondary">
                      <span className="font-mono bg-bg-code border border-border-subtle px-2 py-0.5 rounded text-text-primary">
                        {item.mapping}
                      </span>
                      <span className="font-mono">hash: <code className="text-text-secondary">{item.hash}</code></span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

        </main>

        {/* RIGHT DOCKED COPILOT PANEL */}
        {isCopilotOpen && (
          <aside className="w-[340px] border-l border-border-subtle bg-bg-tertiary flex flex-col justify-between shrink-0 h-full relative">
            
            <div className="p-3.5 border-b border-border-subtle bg-bg-tertiary flex items-center justify-between shrink-0 select-none">
              <div className="flex items-center gap-1.5">
                <Sparkles size={11} className="text-accent-gold" />
                <span className="font-bold text-accent-gold tracking-wider text-[10px] uppercase">COPILOT · QualityControl</span>
              </div>
              <button 
                onClick={() => setIsCopilotOpen(false)}
                className="text-text-secondary hover:text-text-primary text-[10px] font-bold border border-border-subtle px-1 rounded bg-bg-code cursor-pointer"
              >
                ✕
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4 select-text">
              
              {/* Intro Line */}
              <div className="p-3 bg-bg-panel border border-border-subtle rounded space-y-2">
                <p className="text-[10px] text-text-primary leading-relaxed">
                  Ask about this model. Answers come from the graph, not from memory.
                </p>
                <div className="space-y-1.5 pt-2 border-t border-border-subtle">
                  <div className="text-[8px] text-text-secondary uppercase font-bold tracking-widest">Example queries</div>
                  <div className="space-y-1">
                    {[
                      "What does OOS Rate measure?",
                      "What breaks if I change Tests Performed?",
                      "Which joins are inactive?"
                    ].map((promptText, i) => (
                      <button
                        key={i}
                        onClick={() => handleCopilotSubmit(promptText)}
                        className="w-full text-left text-[10px] text-accent-gold hover:underline italic block py-0.5 transition-all cursor-pointer"
                      >
                        "{promptText}"
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Chat Thread */}
              <div className="space-y-4 font-mono text-[10px]">
                {chatLog.map((message, index) => (
                  <div 
                    key={index} 
                    className={`flex flex-col space-y-1 ${message.sender === 'user' ? 'items-end' : 'items-start'}`}
                  >
                    <span className="text-[8px] text-text-secondary uppercase tracking-wider font-bold">
                      {message.sender === 'user' ? 'USER' : 'COPILOT'}
                    </span>
                    <div className={`p-2.5 rounded border leading-relaxed max-w-[95%] whitespace-pre-wrap ${
                      message.sender === 'user' 
                        ? 'bg-bg-secondary border-border-subtle text-accent-gold' 
                        : 'bg-bg-code border-border-subtle text-text-primary'
                    }`}>
                      {message.isThinking ? (
                        <div className="flex items-center gap-1.5 py-1">
                          <span className="inline-block w-1.5 h-1.5 rounded-full bg-accent-gold animate-bounce" style={{ animationDelay: '0ms' }} />
                          <span className="inline-block w-1.5 h-1.5 rounded-full bg-accent-gold animate-bounce" style={{ animationDelay: '150ms' }} />
                          <span className="inline-block w-1.5 h-1.5 rounded-full bg-accent-gold animate-bounce" style={{ animationDelay: '300ms' }} />
                        </div>
                      ) : (
                        message.text
                      )}
                    </div>
                  </div>
                ))}
                <div ref={chatEndRef} />
              </div>

            </div>

            {/* Input drawer box pinned */}
            <div className="p-3 border-t border-border-subtle bg-bg-tertiary shrink-0 select-none">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleCopilotSubmit(copilotInput);
                }}
                className="flex items-center gap-2"
              >
                <input
                  type="text"
                  placeholder="Ask about this model"
                  value={copilotInput}
                  onChange={(e) => setCopilotInput(e.target.value)}
                  className="flex-1 bg-bg-code border border-border-subtle rounded px-3 py-1.5 text-xs text-text-primary focus:outline-none focus:border-accent-gold placeholder-text-secondary font-mono"
                />
              </form>
            </div>

          </aside>
        )}

      </div>
    </div>
  );
}

// Subcomponent for Reconcile card block
interface ReconcileMetricRowProps {
  metric: typeof RECONCILE_METRICS[number];
}

function ReconcileMetricRow({ metric }: ReconcileMetricRowProps) {
  return (
    <div className="bg-bg-panel border border-border-subtle rounded p-4 space-y-3">
      
      <div className="flex justify-between items-center border-b border-border-subtle pb-2 select-none">
        <span className="font-bold text-xs text-text-primary">{metric.name}</span>
        <span className={`text-[8px] font-bold px-1.5 py-0.2 rounded border uppercase ${
          metric.status === 'consistent' ? 'bg-brand-green-bg border-brand-green-border text-brand-green-text' :
          metric.status === 'needs review' ? 'bg-brand-yellow-bg border-brand-yellow-border text-brand-yellow-text' :
          'bg-brand-red-bg border-brand-red-border text-brand-red-text'
        }`}>
          {metric.status}
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        
        {/* Power BI panel */}
        <div className="space-y-1">
          <div className="text-[8px] font-semibold text-text-secondary uppercase">POWER_BI dax</div>
          <div className="bg-bg-code border border-border-subtle rounded p-3 min-h-[60px]">
            <pre className="text-xs text-text-secondary font-mono leading-relaxed whitespace-pre-wrap select-all">{metric.powerBi.code}</pre>
            
            <div className="mt-3 pt-2 border-t border-border-subtle text-[9px] text-text-secondary flex gap-4 font-mono select-none">
              <div>
                <span className="font-bold">reads tables</span>
                <span className="block text-brand-red-text font-semibold mt-0.5">{metric.powerBi.readsTables.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">reads columns</span>
                <span className="block text-text-secondary mt-0.5">{metric.powerBi.readsColumns.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">aggregates</span>
                <span className="block text-text-secondary mt-0.5">{metric.powerBi.aggregates.join(', ')}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Warehouse panel */}
        <div className="space-y-1">
          <div className="text-[8px] font-semibold text-text-secondary uppercase">WAREHOUSE sql</div>
          <div className="bg-bg-code border border-border-subtle rounded p-3 min-h-[60px]">
            <pre className="text-xs text-text-secondary font-mono leading-relaxed whitespace-pre-wrap select-all">{metric.warehouse.code}</pre>
            
            <div className="mt-3 pt-2 border-t border-border-subtle text-[9px] text-text-secondary flex gap-4 font-mono select-none">
              <div>
                <span className="font-bold">reads tables</span>
                <span className="block text-brand-red-text font-semibold mt-0.5">{metric.warehouse.readsTables.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">reads columns</span>
                <span className="block text-text-secondary mt-0.5">{metric.warehouse.readsColumns.join(', ')}</span>
              </div>
              <div>
                <span className="font-bold">aggregates</span>
                <span className="block text-text-secondary mt-0.5">{metric.warehouse.aggregates.join(', ')}</span>
              </div>
            </div>
          </div>
        </div>

      </div>

      <div className="text-[10px] text-text-secondary pt-1.5 font-mono select-text">
        {metric.callout}
      </div>

    </div>
  );
}

export default App;
